### ISSUE TITLE
Binary Linux libzmq.so.3

### ISSUE THREAD

**Issue by 2ge** [vivocoin/vivo#1]
Hi

```
$ vivod -daemon
vivod: error while loading shared libraries: libzmq.so.3: cannot open shared object file: No such file or directory
$ uname -a
Linux Ubuntu-1604-xenial-64-minimal 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I got installed
libzmq3-dev is already the newest version (4.1.4-7).

**Comment by hunbalazs** [comment]
You downloaded the wrong version. That vivo daemon is build for Ubuntu 14.04 you need this file: https://github.com/vivocoin/vivo/releases/download/v0.12.1.7/Vivo-0.12.1.7-ubuntu16.04.tar.gz

**Comment by 2ge** [comment]
thanks

**Comment by trsteel88** [comment]
I am having the same problem but I have Ubuntu 17.04:

```
# vivod -daemon
vivod: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
```

Any ideas?

**Comment by hunbalazs** [comment]
Ubuntu 17.04 have the same major ZMQ version so you probably have to install libzmq5.

**Comment by trsteel88** [comment]
Got it, had to install a few packages

```
apt-get install libminiupnpc-dev libzmq3-dev libevent-pthreads-2.0-5
```
