### ISSUE TITLE
different versions

### ISSUE THREAD

**Issue by 2ge** [vivocoin/vivo#2]
Hi,

https://github.com/vivocoin/vivo/releases/download/v0.12.1.7/Vivo-0.12.1.7-ubuntu16.04.tar.gz
gives me "version": 120106,

https://github.com/vivocoin/vivo/releases/download/v0.12.1.7/Vivo-0.12.1.7-osx.dmg
gives me "version": 120107,

**Comment by whidrasl** [comment]
still 0.12.1.6 for ubuntu 16.04

**Comment by buzztiaan** [comment]
maybe https://github.com/vivocoin/vivo/releases/download/v0.12.1.7/Vivo-0.12.1.7-ubuntu16.04.tar.gz ?

**Comment by vivocoindev** [comment]
fixed in the last release
