### ISSUE TITLE
the wallet release for Ubuntu 16.04 is missing the GUI

### ISSUE THREAD

**Issue by FlorinAndrei** [vivocoin/vivo#3]
vivo-qt is missing from the release made for Ubuntu 16.04

The release for 14.04 does include vivo-qt, but that doesn't work on 16.04:

```
./vivo-qt: error while loading shared libraries: libzmq.so.3: cannot open shared object file: No such file or directory
```

Ubuntu 14.04 is 3.5 years old. It would be hard to go back to such an old distribution only to be able to run Vivo. Please update the release.

**Comment by kaner** [comment]
https://github.com/vivocoin/vivo/releases/download/v0.12.1.7/Vivo-0.12.1.7-ubuntu16.04.tar.gz

**Comment by vivocoindev** [comment]
fixed in the last release

**Comment by HarryPaulo** [comment]
i not working on ubuntu 16.04 with vivo wallet 0.12.1.8 ubuntu 16.04

**Comment by HarryPaulo** [comment]
i used this link https://github.com/vivocoin/vivo/releases/download/v0.12.1.8/Vivo-0.12.1.8-ubuntu16.04.tar.gz

**Comment by HarryPaulo** [comment]
follow the image to you check it


![image](https://user-images.githubusercontent.com/25017988/44378861-99cce280-a4d9-11e8-84bd-06461de8a1b6.png)
