### ISSUE TITLE
Vivo Core Wallet

### ISSUE THREAD

**Issue by quickgibva** [vivocoin/vivo#4]
Hello, i have locked my vivo wallet and i don't know how to unlowk it.

It's asking me a passphrase but i dont remember having to setup one up or anything, is there anyway i can recover my coins ? 

I dont have that much on it like 5.3 coins but still, would be great if i could recover them.

thanks for the help

**Comment by tutunciyan** [comment]
I don't think there is an way around it, which is the whole purpose of locking your wallet. So, you need to remember the passphrase to unlock it.

**Comment by quickgibva** [comment]
Yeah :s but it's really dumb because when i created the wallet, it didn't asked me to remember any passphrase, and then i locked it to see how the locking was working, and boum out of nowhere its asking me for a passphrase, its completly retarded in my opinion.....

**Comment by buzztiaan** [comment]
did you try a empty password?

**Comment by hunbalazs** [comment]
Sorry, this is not a VIVO issue. (comments are still allowed)
