### ISSUE TITLE
Vivo Windows Wallet watchdog_expired

### ISSUE THREAD

**Issue by techliff** [vivocoin/vivo#6]
Hi, how can I fix this error in my vivo wallet (watchdog_expired) ? I'm new so I do not know what to do. I use windows wallet , not vps.
Thank you.

**Comment by RNOVAKOSKY** [comment]
I have the same problem sentinel program is necessary and but devs didint compile the sentinel to windows version. See here: https://github.com/vivocoin/sentinel
Well this is a problem because many ppl will not work with linux never never never ....

**Comment by hunbalazs** [comment]
Please open this issue in sentinel as "Please provide sentinel release for windows".
Workaround: https://github.com/ajkagy/sentinel
